### ISSUE TITLE
Confirming the script works for 21.3 "Virginia"

### ISSUE THREAD

**Issue by GijsvandenHoven** [Rigel2118/pipewire-installation-kit-for-linuxmint#1]
Hello,

There is no issue with your script, you can probably close this issue right away.

I would like to post this to confirm it also works for 21.3!
I landed here after trying some other guides, all of which with contradicting information & bricking my audio (thank you TimeShift for rolling back).

This script actually works and for that I want to thank you. You may want to update the description to mention 21.3, if you trust my words on their own.

Either way, thanks again for this install script.
Seeing the amount of packages in it that I did not encounter in other guides, I suspect you saved me a lot of future problems with audio not working on random devices, even if I eventually got it working by bashing apt commands together myself.

cheers

**Comment by Rigel2118** [comment]
Glad it was useful to you! Thanks for confirming.
